Models/ErrorViewModel.cs
namespace lr9.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TableItem.cs
namespace lr9.Models
{
    public class TableItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    }
}

Models/Weather.cs
namespace lr9.Models
{
    public class Weather
    {
        public Main Main { get; set; }
        public string Name { get; set; }
        public int Id { get; set; }
        public Sys Sys { get; set; }
        public Wind Wind { get; set; }
    }

    public class Main
    {
        public float Temp { get; set; }
        public float Feels_like { get; set; }
        public float Humidity { get; set; }
    }

    public class Sys
    {
        public string Country { get; set; }
    }

    public class Wind
    {
        public double Speed { get; set; }
    }
}

Controllers/HomeController.cs
using lr9.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Dynamic;

namespace lr9.Controllers
{
    public class HomeController : Controller
    {
        private List<TableItem> GetTableItems()
        {
            List<TableItem> list = new List<TableItem>();
            for (var i = 0; i < 10; i++) list.Add(new TableItem { Id = i, Name = $"Product {i}", Price = i * 10 });
            return list;
        }

        public IActionResult Index()
        {
            dynamic model = new ExpandoObject();
            model.TableItems = GetTableItems();
            return View(model);
        }
    }
}

ViewComponents/TableViewComponent.cs
using lr9.Models;
using Microsoft.AspNetCore.Mvc;

namespace lr9.ViewComponents
{
    public class TableViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke(List<TableItem> items)
        {
            return View(items);
        }
    }
}

ViewComponents/WeatherViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using lr9.Models;
using Newtonsoft.Json;

namespace lr9.ViewComponents
{
    public class WeatherViewComponent : ViewComponent
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly string apiKey = "7579433743fb0fad5af7251634769d9b";

        public WeatherViewComponent(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IViewComponentResult> InvokeAsync(string region)
        {
            var request = new HttpRequestMessage(HttpMethod.Get, $"https://api.openweathermap.org/data/2.5/weather?q={region}&appid={apiKey}");
            var client = _httpClientFactory.CreateClient();
            var response = await client.SendAsync(request);

            if (!response.IsSuccessStatusCode) return Content("Unable to retrieve weather data");

            var content = await response.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject<Weather>(content);
            return View(data);

        }
    }
}

Views/Home/Components/Table/Default.cshtml
@using lr9.Models
@model List<TableItem>

<style>
    table {
        width: 100%
    }

    thead {
        font-weight: 600;
    }

    tr {
        border-bottom: 1px solid lightgray;
        min-height: 50px
    }

    th {
        min-width: 100px
    }
</style>

<table>
    <caption></caption>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Price</td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Components/Weather/Default.cshtml
<h4>Погода в @Model.Name, @Model.Sys.Country</h4>
<h5>Температура: @((Model.Main.Temp - 273.15).ToString("0.00"))°C</h5>
<h5>Відчувається як: @((Model.Main.Feels_like - 273.15).ToString("0.00"))°C</h5>
<h5>Вологість: @Model.Main.Humidity %</h5>
<h5>Швидкість вітру: @Model.Wind.Speed m/s S</h5>

Views/Home/Index.cshtml
@addTagHelper *, MvcApp

@await Component.InvokeAsync("Weather", new { region = "Mykolayiv" })

@await Component.InvokeAsync("Table", new { items = Model.TableItems })

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lr9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lr9.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lr9</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - lr9 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>